definitions:
  steps: 
    - step: &Deploy-step
        name: Deploy Step
        script:
          - echo $TEST_VALUE
          - export MYVAR="SEASONED MEAT"
    - step: &Build-step
        name: Test Sub-shell
        script:
          - echo $MYVAR
pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          deployment: production
          <<: *Deploy-step
          <<: *Build-step
