definitions:
  steps: &Deploy-step
    - step:
        name: Deploy Step
        script:
          - echo $TEST_VALUE
          - export MYVAR="SEASONED MEAT"
    - step: 
        name: Test Sub-shell
        script:
          - echo MYVAR
pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          deployment: production
          <<: *Deploy-step
          
    quality-assurance:
      - step:
          name: Deploy to Quality Assurance
          deployment: quality-assurance
          <<: *Deploy-step
