# Define the common deployment steps as an anchor
standardDeploymentSteps: &standardDeploymentSteps
  - step:
      name: Deploy Containers to ECS (Fargate)
      script:
        - echo $ENV_NAME
        - echo $SECURE

pipelines:
  branches:
    main:
      - step:
          - export ENV_NAME=$PRODUCTION_ENV_NAME
      - <<: *standardDeploymentSteps
    quality-assurance:
      - <<: *standardDeploymentSteps
