# Define the common deployment steps as an anchor
standardDeploymentSteps: &standardDeploymentSteps
  script:
    - echo $ENV_NAME

pipelines:
  branches:
    main:
      - step: &deployToProduction
          name: Deploy to Production
          script:
            - export ENV_NAME=$PRODUCTION_ENV_NAME
            - echo "Setting ENV_NAME to $ENV_NAME"
      - step:
          <<: *deployToProduction
          <<: *standardDeploymentSteps
