# Define the common deployment steps as an anchor
standardDeploymentSteps: &standardDeploymentSteps
  - step:
      name: Deploy Containers to ECS (Fargate)
      script:
        - echo $ENV_NAME

pipelines:
  branches:
    main:
      - step:
          name: Pre-Step
          script:
            - export ENV_NAME=$PRODUCTION_ENV_NAME
      - <<: *standardDeploymentSteps