definitions:
  steps:
    - step: &Deploy-step
        name: Deploy Step
        script:
          - echo $TEST_VALUE
pipelines:
  default:
    - step:
        name: Deploy to Quality Assurance
        deployment: quality-assurance
        condition: $BITBUCKET_BRANCH == "quality-assurance"
        <<: *Deploy-step
    - step:
        name: Deploy to Production
        deployment: production
        condition: $BITBUCKET_BRANCH == "main"
        <<: *Deploy-step