pipelines:
  branches:
    main:
      - step: *standardDeploymentSteps
        name: Deploy to Production 
        deployment: production
        script:
          - echo $TEST_VALUE

    quality-assurance:
      - step: *standardDeploymentSteps
        name: Deploy to QA
        deployment: quality-assurance
        script:
          - echo $TEST_VALUE