definitions:
  steps:
    - step: &Test-step
        name: Run tests
        script:
          - echo $GLOBAL_VARIABLE
    - step: &Deploy-step
        name: Deploy to staging
        script:
          - echo $TEST_VALUE
pipelines:
  default:
    - step: *Test-step
    - step:
        <<: *Deploy-step
        name: Deploy to Quality Assurance
        deployment: quality-assurance
  custom:
    Staging Deployment
      - step: *Test-step
      - step:
          <<: *Deploy-step
          deployment: quality-assurance
    Production Deployment
      - step: *Test-step
      - step:
          <<: *Deploy-step
          deployment: production