definitions:
  steps:
    - step: &Deploy-step
        name: Deploy Step
        script:
          - echo $TEST_VALUE
pipelines:
  default:
    - step:
        name: Deploy to Quality Assurance
        deployment: quality-assurance
        <<: *Deploy-step
      condition:
        branches:
          only:
            - quality-assurance
    - step:
        name: Deploy to Production
        deployment: production
        <<: *Deploy-step
      condition:
        branches:
          only:
            - main