pipelines:
  branches:
    main:
      - step:
          name: Deploy Containers to ECS (Fargate) - Production
          script:
            - export ENV_NAME=$PRODUCTION_ENV_NAME
            - echo $ENV_NAME
            # Add deployment steps here

    quality-assurance:
      - step:
          name: Deploy Containers to ECS (Fargate) - QA
          script:
            - export ENV_NAME=$QA_ENV_NAME
            - echo $ENV_NAME
            # Add deployment steps here
