definitions:
  steps:
    - step: &Test-step
        name: Test Step
        script:
          - echo $GLOBAL_VARIABLE
    - step: &Deploy-step
        name: Deploy Step
        script:
          - echo $TEST_VALUE
pipelines:
  default:
    - step: *Test-step
    - step:
        <<: *Deploy-step
        name: Deploy to Quality Assurance
        deployment: quality-assurance