standardDeploymentSteps: &standardDeploymentSteps

  - step:
      name: Deploy Containers to ECS (Fargate)
      script:
        - echo $TEST_VALUE

pipelines:
  default:
    - step:
        name: 'Deployment to Staging'
        deployment: quality-assurance
        script:
          - <<: *standardDeploymentSteps
    - step:
        name: 'Deployment to Production'
        deployment: production
        script:
          - <<: *standardDeploymentSteps
