definitions:
  steps:
    - step: &Deploy-step
        name: Deploy Step
        script:
          - echo $TEST_VALUE
pipelines:
  branches:
    quality-assurance:
      - step:
          name: Deploy to Quality Assurance
          deployment: quality-assurance
          <<: *Deploy-step
